### ISSUE TITLE
⚠ Alpha Countdown ⚠

### ISSUE THREAD

**Issue by crutchcorn** [crutchcorn/GitShark#21]
- [x] Checkout branch
- [x] Branch actions
   - [x] Checkout branch
   - [x] Rename branch: #26
       - [x] Rename branch dialog
   - [x] Delete branch
       - [x] Confirmation dialog
   - [x] Menu UI (easy)
- [x] Create branch
- [x] Test push logic
- [x] push (requires https://github.com/isomorphic-git/isomorphic-git/issues/233)
    - [x] Push dialog
         - [x] Pre-fill push dialog with current info
- [x] fetch
    - [x] fetch dialog
         - [x] ~~Pre-fill fetch dialog with current info~~
- [x] Rename repo from repository screen
- [x] Hook up push/pull numbers
- [x] Get commit list push/pull indicators working
- [x] Git Add Bug: #17
- [x] Git add removed file bug: (#29)
- [x] Fix timestamp on commit list
- [x] ~~Add commit progress dialog~~ (No `isomorphic-git` option for this)
- [x] Add dialog when no username and name associated during commit
- [x] Temporarily remove the "Add new" remotes button
- [x] Checkout remote branch
- [x] Add warning dialog when checking out with existing files
- [x] Add snackbar of "coming soon" to ignore in file list
- [x] Add discard action on file list
- [x] Add checkout `onProgress` dialog
- [x] pull
    - [x] ~~Pull dialog~~ (Upon reflection, I've decided that this needlessly makes the UI more complex and will not be including it for the alpha)
   - [x] Pull progress dialog
- [x] #33

**Comment by crutchcorn** [comment]
Moving the items we're aiming for alpha 2 into this comment to avoid confusion:

- [ ] Merge branch
    - [ ] Partial merge support #20 
- [ ] Checkout commit
- [ ] Add remote
    - [ ] Add remote dialog
